development:
    app_id: "401321467006-kf6fnhlheessgb232b5bplgtcaqdnagk.apps.googleusercontent.com"
    secret: "ZPNVAY2MVG5ZRVLhNnlky7bv"

production:
    app_id: "401321467006-kf6fnhlheessgb232b5bplgtcaqdnagk.apps.googleusercontent.com"
    secret: "ZPNVAY2MVG5ZRVLhNnlky7bv"